image: docker:dind

stages:
  - build

.base:
  stage: build
  variables:
    PHP_VERSION: ""
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:$PHP_VERSION-alpine ./$PHP_VERSEION-alpine
    - docker push $CI_REGISTRY_IMAGE:$PHP_VERSION-alpine
  after_script:
    - docker rmi -f $CI_REGISTRY_IMAGE:$PHP_VERSION-alpine

"5.6":
  extends: .base
  variables:
    PHP_VERSION: "5.6"

"7.0":
  extends: .base
  variables:
    PHP_VERSION: "7.0"

"7.1":
  extends: .base
  variables:
    PHP_VERSION: "7.1"

"7.2":
  extends: .base
  variables:
    PHP_VERSION: "7.2"

"7.3":
  extends: .base
  variables:
    PHP_VERSION: "7.3"
